version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    container_name: app-lumen
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/backend/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    container_name: web-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/backend/:/var/www/html

  db:
    container_name: mysql-80
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
  node:
    container_name: node-react
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
    - ./src/frontend/:/usr/src/app
    command: sh -c "cd frontend && npm start"
    ports:
    - "3000:3000"
